export const admin = {
  appName: "NovelGen 管理后台",
  nav: {
    dashboard: "概览",
    users: "用户",
    teams: "团队",
    modelConfigs: "模型配置",
    schemas: "分析模板",
    templates: "大纲模板",
    monitoring: "监控",
    audit: "审计日志",
    alerts: "告警规则",
    concurrency: "并发配置",
    logout: "登出",
  },
  errors: {
    forbidden: "无权访问",
    conflict: "已被他人更新，请刷新后重试",
    networkUnavailable: "服务暂时不可用，请稍后重试",
  },
  actions: {
    save: "保存",
    cancel: "取消",
    refresh: "刷新",
    confirm: "确认",
    delete: "删除",
    disable: "禁用",
    enable: "启用",
    rename: "改名",
    resetPassword: "重置密码",
    promoteAdmin: "提升为管理员",
  },
  stages: {
    classification: "类型分类",
    character: "人物",
    map: "地图",
    style: "风格",
    outline: "大纲",
    chapter: "章节",
    self_critique: "自检",
    critic: "评审",
    consistency: "一致性",
  },
} as const;
